
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testmybatis?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: liu3.1415926


  jpa:
    hibernate:
      #自动创建|更新|验证数据库表结构
      ddl-auto: update
      #设置数据库引擎为InnoDB
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      #打印sql语句，方便调试
      show-sql: true
