
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testmybatis?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: liu3.1415926
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  config-location: classpath:mybatis-config.xml




